version: "3.8"
services:
  mssql:
    container_name: db-mssql
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    user: root
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Iot@@123
    volumes:
        - ./data:/var/opt/mssql
  web:
    restart: unless-stopped
    depends_on: 
        - mssql
    container_name: dms-be
    image: 'dms-be:latest'
    ports:
        - '8080:8080'
networks:
    default:
        external: true
        name: dms-nw